version: '3'

services:
  
  transaction-service:
    image: transaction-service:1
    ports:
      - 8080:8080
    depends_on:
      - schedule-service
    environment:
      - DATABASE_HOST=172.16.9.192
      - DATABASE_PORT=3306
      - DATABASE_NAME=ARTSDEV
      - DATABASE_USER=gemuruhgeo
      - DATABASE_PASSWORD=Maryam@1219
  schedule-service:
    image: schedule-service:1
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=172.16.9.192
      - DATABASE_PORT=3306
      - DATABASE_NAME=ARTSDEV
      - DATABASE_USER=gemuruhgeo
      - DATABASE_PASSWORD=Maryam@1219

